[package]
name = "ex_finder"
version = "1.0.0"
edition = "2024"
repository = "https://github.com/mpack606/ex_finder"

[dependencies]
chrono = "0.4.45"
dirs = "6.0.0"
iced = { version = "0.14.0", features = ["tokio", "svg", "image"] }
image = { version = "0.25.10", default-features = false, features = ["png"] }
open = "5.3.5"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.49.0", features = ["rt", "time"] }
toml = "1.1.2"
trash = "5.1.2"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.4"
objc2-app-kit = { version = "0.3.2", default-features = false, features = ["NSWorkspace", "NSImage", "NSBitmapImageRep", "NSImageRep", "NSGraphicsContext", "objc2-core-graphics"] }
objc2-foundation = { version = "0.3.2", default-features = false, features = ["NSURL", "NSDictionary"] }

[package.metadata.bundle]
name = "ExFinder"
identifier = "com.mpack606.ex_finder"
icon = ["src/assets/icon.png"]
version = "0.1.0"
copyright = "Copyright © 2024. All rights reserved."
category = "Utility"
short_description = "A lightweight macOS Finder replacement built with Rust."

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
